$base = "d:\Arpa\self_project\byabshaTrack\resources\lang"

# EN - sale.php
Set-Content "$base\en\sale.php" -Encoding UTF8 -Value @'
<?php


















































































































































































































































































































































































































































































































































Write-Host "All BN files done. Now syntax checking..."'@];    'tab_shops'          => 'দোকান',    'tab_products'       => 'পণ্য',    'tab_sales'          => 'বিক্রয়',    'daily_trends'       => 'দৈনিক প্রবণতা',    'top_products'       => 'শীর্ষ পণ্য',    'table_stock_profit' => 'সম্ভাব্য লাভ',    'table_stock_value'  => 'স্টক মূল্য',    'table_stock_qty'    => 'স্টক পরিমাণ',    'table_sale_price'   => 'বিক্রয় মূল্য',    'table_purchase'     => 'ক্রয় মূল্য',    'table_stock_shop'   => 'দোকান',    'table_stock_product'=> 'পণ্য',    'stock_summary'      => 'স্টক সারসংক্ষেপ',    'no_data'            => 'নির্বাচিত ফিল্টারের জন্য কোনো তথ্য পাওয়া যায়নি।',    'table_profit'       => 'লাভ',    'table_total'        => 'মোট পরিমাণ',    'table_price'        => 'বিক্রয় মূল্য',    'table_qty'          => 'পরিমাণ',    'table_product'      => 'পণ্য',    'table_shop'         => 'দোকান',    'table_date'         => 'তারিখ',    'sales_table'        => 'বিক্রয় প্রতিবেদন',    'profit_margin'      => 'লাভের মার্জিন',    'total_sales'        => 'মোট বিক্রয়',    'total_cost'         => 'মোট খরচ',    'total_profit'       => 'মোট লাভ',    'total_revenue'      => 'মোট আয়',    'summary_title'      => 'সারসংক্ষেপ',    'reset'              => 'রিসেট',    'apply'              => 'ফিল্টার প্রয়োগ',    'filter_date_to'     => 'তারিখ পর্যন্ত',    'filter_date_from'   => 'তারিখ থেকে',    'all_shops'          => 'সব দোকান',    'filter_shop'        => 'দোকান',    'filter_title'       => 'ফিল্টার',    'subtitle'           => 'আপনার ব্যবসার কর্মক্ষমতা বিশ্লেষণ করুন',    'title'              => 'প্রতিবেদন',return [<?phpSet-Content "$base\bn\report.php" -Encoding UTF8 -Value @'# BN - report.php'@];    'updated_at'         => 'সর্বশেষ আপডেট',    'capital_formula'    => 'স্টক পরিমাণ × ক্রয় মূল্য',    'no_shops'           => 'কোনো দোকান পাওয়া যায়নি।',    'no_products'        => 'এই দোকানে কোনো পণ্য নেই।',    'table_subtotal'     => 'সাবটোটাল',    'table_value'        => 'স্টক মূল্য',    'table_purchase'     => 'ক্রয় মূল্য',    'table_stock'        => 'স্টক পরিমাণ',    'table_product'      => 'পণ্য',    'breakdown_title'    => 'মূলধনের বিভাজন',    'breakdown'          => 'বিভাজন দেখুন',    'stock_value'        => 'স্টক মূল্য',    'products_count'     => 'পণ্য',    'shop_name'          => 'দোকান',    'shop_capital'       => 'দোকান অনুযায়ী মূলধন',    'total_capital'      => 'মোট মূলধন',    'formula_desc'       => 'আপনার মোট মূলধন হল ক্রয় খরচে সমস্ত অবিক্রীত ইনভেন্টরির মূল্য।',    'formula_banner'     => 'মূলধন = যোগফল (স্টক পরিমাণ × ক্রয় মূল্য)',    'subtitle'           => 'আপনার ব্যবসার মূলধন এবং ইনভেন্টরি মূল্য ট্র্যাক করুন',    'title'              => 'মূলধন',return [<?phpSet-Content "$base\bn\capital.php" -Encoding UTF8 -Value @'# BN - capital.php'@];    'step_profit'        => 'লাভ',    'step_total'         => 'মোট পরিমাণ',    'step_by_step'       => 'ধাপে ধাপে গণনা',    'apply_filters'      => 'ফিল্টার প্রয়োগ',    'all_shops'          => 'সব দোকান',    'filter_date_to'     => 'তারিখ পর্যন্ত',    'filter_date_from'   => 'তারিখ থেকে',    'filter_shop'        => 'দোকান অনুযায়ী ফিল্টার',    'updated'            => 'বিক্রয় সফলভাবে আপডেট হয়েছে।',    'created'            => 'বিক্রয় সফলভাবে রেকর্ড হয়েছে।',    'deleted'            => 'বিক্রয় সফলভাবে মুছে ফেলা হয়েছে।',    'total_profit'       => 'মোট লাভ',    'total_revenue'      => 'মোট আয়',    'page_totals'        => 'পৃষ্ঠার মোট',    'formula_legend'     => 'সূত্র',    'profit_formula'     => 'লাভ = (বিক্রয় - ক্রয়) × পরিমাণ',    'total_formula'      => 'মোট = পরিমাণ × বিক্রয় মূল্য',    'calc_preview'       => 'গণনার পূর্বদর্শন',    'stock_after'        => 'পরের স্টক',    'stock_before'       => 'আগের স্টক',    'margin'             => 'মার্জিন',    'purchase_price'     => 'ক্রয় মূল্য',    'profit'             => 'লাভ',    'total_amount'       => 'মোট পরিমাণ',    'sale_info'          => 'বিক্রয়ের তথ্য',    'create_first'       => 'শুরু করতে প্রথম বিক্রয় রেকর্ড করুন।',    'no_sales'           => 'কোনো বিক্রয় পাওয়া যায়নি।',    'table_actions'      => 'কার্যক্রম',    'table_profit'       => 'লাভ',    'table_total'        => 'মোট পরিমাণ',    'table_price'        => 'বিক্রয় মূল্য',    'table_qty'          => 'পরিমাণ',    'table_product'      => 'পণ্য',    'table_shop'         => 'দোকান',    'table_date'         => 'তারিখ',    'update_btn'         => 'বিক্রয় আপডেট করুন',    'save_btn'           => 'বিক্রয় সংরক্ষণ করুন',    'notes_placeholder'  => 'যেকোনো অতিরিক্ত নোট',    'notes'              => 'নোট (ঐচ্ছিক)',    'sale_date'          => 'বিক্রয়ের তারিখ',    'price_placeholder'  => 'প্রতি ইউনিটে বিক্রয় মূল্য লিখুন',    'sale_price'         => 'বিক্রয় মূল্য',    'qty_placeholder'    => 'পরিমাণ লিখুন',    'quantity'           => 'পরিমাণ',    'select_product'     => 'একটি পণ্য নির্বাচন করুন',    'product'            => 'পণ্য',    'select_shop'        => 'একটি দোকান নির্বাচন করুন',    'shop'               => 'দোকান',    'show_title'         => 'বিক্রয়ের বিস্তারিত',    'edit_title'         => 'বিক্রয় সম্পাদনা',    'create_title'       => 'নতুন বিক্রয় রেকর্ড করুন',    'add_sale'           => 'নতুন বিক্রয় যোগ করুন',    'title'              => 'বিক্রয়',return [<?phpSet-Content "$base\bn\sale.php" -Encoding UTF8 -Value @'# BN - sale.phpWrite-Host "BN shop+product done"'@];    'total_stock_val'   => 'মোট স্টক মূল্য',    'low_stock_count'   => 'কম স্টক আইটেম',    'total_products'    => 'মোট পণ্য',    'quick_stats'       => 'দ্রুত পরিসংখ্যান',    'all_shops'         => 'সব দোকান',    'filter_shop'       => 'দোকান অনুযায়ী ফিল্টার',    'updated'           => 'পণ্য সফলভাবে আপডেট হয়েছে।',    'created'           => 'পণ্য সফলভাবে তৈরি হয়েছে।',    'deleted'           => 'পণ্য সফলভাবে মুছে ফেলা হয়েছে।',    'capital_formula'   => 'স্টক × ক্রয় মূল্য',    'total_stock_value' => 'মোট স্টক মূল্য',    'profit_margin'     => 'লাভের মার্জিন',    'profit_per_unit'   => 'প্রতি ইউনিটে লাভ',    'in_stock'          => 'স্টকে আছে',    'out_of_stock'      => 'স্টক শেষ',    'low_stock_alert'   => 'কম স্টক',    'product_info'      => 'পণ্যের তথ্য',    'create_first'      => 'শুরু করতে প্রথম পণ্য যোগ করুন।',    'no_products'       => 'কোনো পণ্য পাওয়া যায়নি।',    'table_actions'     => 'কার্যক্রম',    'table_margin'      => 'মার্জিন %',    'table_profit_unit' => 'প্রতি ইউনিটে লাভ',    'table_stock'       => 'স্টক',    'table_sale'        => 'বিক্রয় মূল্য',    'table_purchase'    => 'ক্রয় মূল্য',    'table_shop'        => 'দোকান',    'table_name'        => 'পণ্যের নাম',    'update_btn'        => 'পণ্য আপডেট করুন',    'save_btn'          => 'পণ্য সংরক্ষণ করুন',    'desc_placeholder'  => 'ঐচ্ছিক পণ্যের বিবরণ',    'description'       => 'বিবরণ',    'stock'             => 'স্টক পরিমাণ',    'sale_price'        => 'বিক্রয় মূল্য',    'purchase_price'    => 'ক্রয় মূল্য',    'select_shop'       => 'একটি দোকান নির্বাচন করুন',    'shop'              => 'দোকান',    'name_placeholder'  => 'পণ্যের নাম লিখুন',    'name'              => 'পণ্যের নাম',    'show_title'        => 'পণ্যের বিস্তারিত',    'edit_title'        => 'পণ্য সম্পাদনা',    'create_title'      => 'নতুন পণ্য যোগ করুন',    'add_product'       => 'নতুন পণ্য যোগ করুন',    'title'             => 'পণ্যসমূহ',return [<?phpSet-Content "$base\bn\product.php" -Encoding UTF8 -Value @'# BN - product.php'@];    'updated'          => 'দোকান সফলভাবে আপডেট হয়েছে।',    'created'          => 'দোকান সফলভাবে তৈরি হয়েছে।',    'deleted'          => 'দোকান সফলভাবে মুছে ফেলা হয়েছে।',    'products'         => 'এই দোকানের পণ্য',    'updated_at'       => 'সর্বশেষ আপডেট',    'created_at'       => 'তৈরির তারিখ',    'shop_info'        => 'দোকানের তথ্য',    'total_profit'     => 'মোট লাভ',    'total_revenue'    => 'মোট আয়',    'total_capital'    => 'মোট মূলধন',    'total_sales'      => 'মোট বিক্রয়',    'total_products'   => 'মোট পণ্য',    'create_first'     => 'শুরু করতে প্রথম দোকান তৈরি করুন।',    'no_shops'         => 'কোনো দোকান পাওয়া যায়নি।',    'table_actions'    => 'কার্যক্রম',    'table_created'    => 'তৈরির তারিখ',    'table_products'   => 'পণ্য',    'table_status'     => 'অবস্থা',    'table_phone'      => 'ফোন',    'table_address'    => 'ঠিকানা',    'table_name'       => 'দোকানের নাম',    'update_btn'       => 'দোকান আপডেট করুন',    'save_btn'         => 'দোকান সংরক্ষণ করুন',    'inactive'         => 'নিষ্ক্রিয়',    'active'           => 'সক্রিয়',    'status'           => 'অবস্থা',    'phone_placeholder'=> 'ফোন নম্বর লিখুন',    'phone'            => 'ফোন নম্বর',    'addr_placeholder' => 'দোকানের ঠিকানা লিখুন',    'address'          => 'ঠিকানা',    'desc_placeholder' => 'দোকানের বিবরণ লিখুন (ঐচ্ছিক)',    'description'      => 'বিবরণ',    'name_placeholder' => 'দোকানের নাম লিখুন',    'name'             => 'দোকানের নাম',    'show_title'       => 'দোকানের বিস্তারিত',    'edit_title'       => 'দোকান সম্পাদনা',    'create_title'     => 'নতুন দোকান তৈরি করুন',    'add_shop'         => 'নতুন দোকান যোগ করুন',    'title'            => 'দোকানসমূহ',return [<?phpSet-Content "$base\bn\shop.php" -Encoding UTF8 -Value @'# BN - shop.phpWrite-Host "BN auth+dashboard done"'@];    'capital_val'          => 'যোগফল স্টক × ক্রয় মূল্য',    'monthly_val'          => 'যোগফল এই মাসের লাভ',    'profit_val'           => 'যোগফল (বিক্রয়-ক্রয়)×পরিমাণ আজ',    'total_amount_val'     => 'যোগফল মোট পরিমাণ আজ',    'no_sales'             => 'কোনো বিক্রয় পাওয়া যায়নি।',    'no_products'          => 'কোনো পণ্য পাওয়া যায়নি।',    'recent_sales'         => 'সাম্প্রতিক বিক্রয়',    'recent_products'      => 'সাম্প্রতিক পণ্য',    'current_capital'      => 'বর্তমান মূলধন',    'total_sales_count'    => 'মোট বিক্রয়',    'shop_details'         => 'দোকানের বিস্তারিত',    'create_first_shop'    => 'মেট্রিক্স দেখতে প্রথম দোকান তৈরি করুন।',    'no_shops'             => 'কোনো দোকান পাওয়া যায়নি',    'show_details'         => 'বিস্তারিত দেখুন',    'capital'              => 'মূলধন',    'monthly_profit'       => 'মাসিক লাভ',    'todays_profit'        => 'আজকের লাভ',    'todays_sales'         => 'আজকের বিক্রয়',    'shop_performance'     => 'দোকানের কর্মক্ষমতা',    'capital_desc'         => 'সমস্ত পণ্যের ক্রয় মূল্যে অবিক্রীত ইনভেন্টরির মোট মূল্য।',    'capital_formula_full' => '= যোগফল (স্টক পরিমাণ × ক্রয় মূল্য)',    'capital_title'        => 'মূলধন (প্রতি দোকান)',    'profit_desc'          => 'বিক্রয় খরচ কেটে নিট উপার্জন।',    'profit_formula_full'  => '= (বিক্রয় মূল্য - ক্রয় মূল্য) × পরিমাণ',    'profit_title'         => 'লাভ',    'revenue_desc'         => 'বিক্রিত পণ্যের বিক্রয় মূল্য, খরচ বাদ দেওয়ার আগে।',    'revenue_formula_full' => '= পরিমাণ × বিক্রয় মূল্য',    'revenue_title'        => 'আয় / মোট পরিমাণ',    'how_calculated'       => 'এই সংখ্যাগুলি কীভাবে গণনা করা হয়?',    'low_stock_desc'       => 'স্টক ≤ ৫ ইউনিট পণ্য',    'profit_formula'       => 'যোগফল (বিক্রয় - ক্রয়) × পরিমাণ আজ',    'revenue_formula'      => 'যোগফল (পরিমাণ × বিক্রয় মূল্য) আজ',    'sales_count_today'    => 'আজকের বিক্রয় রেকর্ড সংখ্যা',    'low_stock'            => 'কম স্টক',    'profit_today'         => 'আজকের লাভ',    'revenue_today'        => 'আজকের আয়',    'sales_today'          => 'আজকের বিক্রয়',    'total_products'       => 'মোট পণ্য',    'total_shops'          => 'মোট দোকান',    'subtitle'             => 'স্বাগতম! এখানে আপনার ব্যবসার কর্মক্ষমতার একটি ওভারভিউ।',    'title'                => 'ড্যাশবোর্ড',return [<?phpSet-Content "$base\bn\dashboard.php" -Encoding UTF8 -Value @'# BN - dashboard.php'@];    'copyright'       => 'ব্যবসা ট্র্যাকিং সিস্টেম',    'back_to_home'    => 'হোমে ফিরুন',    'or'              => 'অথবা',    'demo_label'      => 'admin@byabsha.com / password',    'use_demo'        => 'ডেমো ক্রেডেনশিয়াল ব্যবহার করুন',    'sign_in'         => 'সাইন ইন',    'remember_me'     => 'মনে রাখুন',    'enter_password'  => 'আপনার পাসওয়ার্ড লিখুন',    'password'        => 'পাসওয়ার্ড',    'enter_email'     => 'আপনার ইমেইল লিখুন',    'email_address'   => 'ইমেইল ঠিকানা',    'demo_available'  => 'ডেমো ক্রেডেনশিয়াল পাওয়া যাচ্ছে',    'sign_in_sub'     => 'আপনার ব্যবসা ড্যাশবোর্ড অ্যাক্সেস করতে সাইন ইন করুন',    'welcome_back'    => 'স্বাগতম',    'page_title'      => 'সাইন ইন - ব্যবসা ট্র্যাক',return [<?phpSet-Content "$base\bn\auth.php" -Encoding UTF8 -Value @'# BN - auth.phpWrite-Host "BN app+landing done"'@];    'footer_built'     => 'Laravel ও Bootstrap 5 দিয়ে তৈরি • মডুলার ব্যবসা ট্র্যাকিং সিস্টেম',    'cta_btn'          => 'ড্যাশবোর্ডে সাইন ইন করুন',    'cta_sub'          => 'এখনই সাইন ইন করুন এবং আপনার ব্যবসার কর্মক্ষমতার সম্পূর্ণ দৃশ্য পান।',    'cta_title'        => 'আপনার ব্যবসা ট্র্যাক করতে প্রস্তুত?',    'feat6_desc'       => 'একটি ড্যাশবোর্ড থেকে একাধিক দোকান পরিচালনা করুন।',    'feat6_title'      => 'মাল্টি-শপ সাপোর্ট',    'feat5_desc'       => 'দোকান ও তারিখ অনুযায়ী ফিল্টার করুন। বিক্রয় সারসংক্ষেপ, শীর্ষ পণ্য দেখুন।',    'feat5_title'      => 'প্রতিবেদন ও বিশ্লেষণ',    'feat4_desc'       => 'দোকানের মূলধন স্বয়ংক্রিয়ভাবে স্টক × ক্রয় মূল্য হিসাবে গণনা করা হয়।',    'feat4_title'      => 'মূলধন ট্র্যাকিং',    'feat3_desc'       => 'ক্রয় মূল্য, বিক্রয় মূল্য এবং স্টক পরিমাণ সহ পণ্য ট্র্যাক করুন।',    'feat3_title'      => 'পণ্য ও স্টক',    'feat2_desc'       => 'স্বয়ংক্রিয় স্টক কাটা এবং লাভ গণনা সহ বিক্রয় রেকর্ড করুন।',    'feat2_title'      => 'বিক্রয় ব্যবস্থাপনা',    'feat1_desc'       => 'আপনার সমস্ত দোকানের রিয়েল-টাইম ওভারভিউ পান। আজকের বিক্রয়, লাভ এবং মূলধন একনজরে দেখুন।',    'feat1_title'      => 'লাইভ ড্যাশবোর্ড',    'features_sub'     => 'পণ্য ব্যবস্থাপনা থেকে লাভ ট্র্যাকিং পর্যন্ত — ব্যবসা ট্র্যাক আপনার ব্যবসার প্রতিটি দিক কভার করে।',    'features_title'   => 'আপনার ব্যবসা পরিচালনার জন্য যা প্রয়োজন',    'features_badge'   => 'বৈশিষ্ট্যসমূহ',    'feat_secure'      => 'নিরাপদ এবং নির্ভরযোগ্য',    'feat_profit'      => 'লাভ ট্র্যাকিং',    'feat_analytics'   => 'রিয়েল-টাইম বিশ্লেষণ',    'get_started'      => 'শুরু করুন',    'go_to_dashboard'  => 'ড্যাশবোর্ড',    'sign_in'          => 'সাইন ইন',    'v1_live'          => 'v1.0 লাইভ',    'nav_get_started'  => 'শুরু করুন',    'nav_features'     => 'বৈশিষ্ট্য',    'capital_sync'     => 'মূলধন সিঙ্ক',    'auto'             => 'স্বয়ংক্রিয়',    'real_time_label'  => 'বিশ্লেষণ',    'real_time'        => 'রিয়েল-টাইম',    'modules'          => 'মডিউল',    'see_features'     => 'বৈশিষ্ট্য দেখুন',    'start_tracking'   => 'ট্র্যাকিং শুরু করুন',    'hero_desc'        => 'ব্যবসা ট্র্যাক একটি শক্তিশালী, মডুলার ব্যবসা ট্র্যাকিং সিস্টেম। দোকান, পণ্য, বিক্রয় এবং মূলধন — সব একটি জায়গায় রিয়েল-টাইম তথ্য সহ।',    'hero_title_2'     => 'ট্র্যাক করুন আগের মতো নয়',    'hero_title_hl'    => 'ব্যবসা',    'hero_title_1'     => 'আপনার',    'smart_business'   => 'স্মার্ট ব্যবসা ব্যবস্থাপনা',    'page_title'       => 'ব্যবসা ট্র্যাক - স্মার্ট ব্যবসা ট্র্যাকিং সিস্টেম',return [<?phpSet-Content "$base\bn\landing.php" -Encoding UTF8 -Value @'# BN - landing.php'@];    'confirm_delete'  => 'আপনি কি নিশ্চিত যে এটি মুছতে চান? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',    'info'            => 'তথ্য',    'warning'         => 'সতর্কতা',    'error'           => 'ত্রুটি',    'success'         => 'সফল',    'loading'         => 'লোড হচ্ছে...',    'no_data'         => 'কোনো তথ্য পাওয়া যায়নি',    'updated_at'      => 'সর্বশেষ আপডেট',    'created_at'      => 'তৈরির তারিখ',    'status'          => 'অবস্থা',    'name'            => 'নাম',    'no'              => 'না',    'yes'             => 'হ্যাঁ',    'apply_filters'   => 'ফিল্টার প্রয়োগ',    'filter'          => 'ফিল্টার',    'search'          => 'অনুসন্ধান',    'update'          => 'আপডেট',    'create'          => 'তৈরি করুন',    'actions'         => 'কার্যক্রম',    'view'            => 'দেখুন',    'delete'          => 'মুছুন',    'edit'            => 'সম্পাদনা',    'cancel'          => 'বাতিল',    'save'            => 'সংরক্ষণ করুন',    'back_to_list'    => 'তালিকায় ফিরুন',    'back'            => 'ফিরে যান',    'reports'         => 'প্রতিবেদন',    'capitals'        => 'মূলধন',    'sales'           => 'বিক্রয়',    'products'        => 'পণ্যসমূহ',    'shops'           => 'দোকানসমূহ',    'dashboard'       => 'ড্যাশবোর্ড',    'analytics'       => 'বিশ্লেষণ',    'management'      => 'ব্যবস্থাপনা',    'main_menu'       => 'মূল মেনু',    'bangla'          => 'বাংলা',    'english'         => 'English',    'language'        => 'ভাষা',    'logout'          => 'লগআউট',    'brand'           => 'ব্যবসা ট্র্যাক',return [<?phpSet-Content "$base\bn\app.php" -Encoding UTF8 -Value @'# BN - app.phpWrite-Host "EN files written."'@];    'updated_at'         => 'Last updated',    'capital_formula'    => 'Stock Qty x Purchase Price',    'no_shops'           => 'No shops found.',    'no_products'        => 'No products in this shop.',    'table_subtotal'     => 'Subtotal',    'table_value'        => 'Stock Value',    'table_purchase'     => 'Purchase Price',    'table_stock'        => 'Stock Qty',    'table_product'      => 'Product',    'breakdown_title'    => 'Capital Breakdown',    'breakdown'          => 'View Breakdown',    'stock_value'        => 'Stock Value',    'products_count'     => 'Products',    'shop_name'          => 'Shop',    'shop_capital'       => 'Capital by Shop',    'total_capital'      => 'Total Capital',    'formula_desc'       => 'Your total capital is the value of all unsold inventory at purchase cost.',    'formula_banner'     => 'Capital = Sum (Stock Qty x Purchase Price)',    'subtitle'           => 'Track your business capital and inventory value',    'title'              => 'Capital',return [<?phpSet-Content "$base\en\capital.php" -Encoding UTF8 -Value @'# EN - capital.php (recreate to be safe)'@];    'tab_shops'          => 'Shops',    'tab_products'       => 'Products',    'tab_sales'          => 'Sales',    'daily_trends'       => 'Daily Trends',    'top_products'       => 'Top Products',    'table_stock_profit' => 'Potential Profit',    'table_stock_value'  => 'Stock Value',    'table_stock_qty'    => 'Stock Qty',    'table_sale_price'   => 'Sale Price',    'table_purchase'     => 'Purchase Price',    'table_stock_shop'   => 'Shop',    'table_stock_product'=> 'Product',    'stock_summary'      => 'Stock Summary',    'no_data'            => 'No data found for selected filters.',    'table_profit'       => 'Profit',    'table_total'        => 'Total Amount',    'table_price'        => 'Sale Price',    'table_qty'          => 'Qty',    'table_product'      => 'Product',    'table_shop'         => 'Shop',    'table_date'         => 'Date',    'sales_table'        => 'Sales Report',    'profit_margin'      => 'Profit Margin',    'total_sales'        => 'Total Sales',    'total_cost'         => 'Total Cost',    'total_profit'       => 'Total Profit',    'total_revenue'      => 'Total Revenue',    'summary_title'      => 'Summary',    'reset'              => 'Reset',    'apply'              => 'Apply Filters',    'filter_date_to'     => 'Date To',    'filter_date_from'   => 'Date From',    'all_shops'          => 'All Shops',    'filter_shop'        => 'Shop',    'filter_title'       => 'Filters',    'subtitle'           => 'Analyze your business performance',    'title'              => 'Reports',return [<?phpSet-Content "$base\en\report.php" -Encoding UTF8 -Value @'# EN - report.php'@];    'step_profit'        => 'Profit',    'step_total'         => 'Total Amount',    'step_by_step'       => 'Step-by-Step Calculation',    'apply_filters'      => 'Apply Filters',    'all_shops'          => 'All Shops',    'filter_date_to'     => 'Date To',    'filter_date_from'   => 'Date From',    'filter_shop'        => 'Filter by Shop',    'updated'            => 'Sale updated successfully.',    'created'            => 'Sale recorded successfully.',    'deleted'            => 'Sale deleted successfully.',    'total_profit'       => 'Total Profit',    'total_revenue'      => 'Total Revenue',    'page_totals'        => 'Page Totals',    'formula_legend'     => 'Formulas',    'profit_formula'     => 'Profit = (Sale - Purchase) x Qty',    'total_formula'      => 'Total = Qty x Sale Price',    'calc_preview'       => 'Calculation Preview',    'stock_after'        => 'Stock After',    'stock_before'       => 'Stock Before',    'margin'             => 'Margin',    'purchase_price'     => 'Purchase Price',    'profit'             => 'Profit',    'total_amount'       => 'Total Amount',    'sale_info'          => 'Sale Information',    'create_first'       => 'Record your first sale to get started.',    'no_sales'           => 'No sales found.',    'table_actions'      => 'Actions',    'table_profit'       => 'Profit',    'table_total'        => 'Total Amount',    'table_price'        => 'Sale Price',    'table_qty'          => 'Qty',    'table_product'      => 'Product',    'table_shop'         => 'Shop',    'table_date'         => 'Date',    'update_btn'         => 'Update Sale',    'save_btn'           => 'Save Sale',    'notes_placeholder'  => 'Any additional notes',    'notes'              => 'Notes (Optional)',    'sale_date'          => 'Sale Date',    'price_placeholder'  => 'Enter sale price per unit',    'sale_price'         => 'Sale Price',    'qty_placeholder'    => 'Enter quantity',    'quantity'           => 'Quantity',    'select_product'     => 'Select a product',    'product'            => 'Product',    'select_shop'        => 'Select a shop',    'shop'               => 'Shop',    'show_title'         => 'Sale Details',    'edit_title'         => 'Edit Sale',    'create_title'       => 'Record New Sale',    'add_sale'           => 'Add New Sale',    'title'              => 'Sales',return [
