<!DOCTYPE html>









































</html></body>    </div>        <p>If you can read this, Laravel is rendering views correctly.</p>        <h1>Blade is working</h1>    <div class="card"><body></head>    </style>        }            color: #cbd5e1;            margin: 0;        p {        }            font-size: 2rem;            margin: 0 0 0.5rem;        h1 {        }            text-align: center;            box-shadow: 0 20px 50px rgba(0, 0, 0, 0.3);            border: 1px solid rgba(148, 163, 184, 0.25);            background: rgba(15, 23, 42, 0.9);            border-radius: 16px;            padding: 2rem 2.5rem;        .card {        }            color: #f8fafc;            background: #0f172a;            font-family: Arial, sans-serif;            place-items: center;            display: grid;            min-height: 100vh;            margin: 0;        body {    <style>    <title>Debug Ping</title>    <meta name="viewport" content="width=device-width, initial-scale=1">    <meta charset="utf-8"><head><html lang="en">

